#!/usr/bin/env bash
set -euo pipefail

# ─── Resonance Server Setup ──────────────────────────────────────────
# Run this once on the 'apps' server (10.0.0.120) to:
#   1. Clone the repo
#   2. Generate production secrets
#   3. Install a GitHub Actions self-hosted runner
#
# Prerequisites:
#   - Docker and Docker Compose installed
#   - Git installed
#   - A GitHub personal access token (for runner registration)
#
# Usage:
#   curl -sL <raw-url-to-this-script> | bash
#   — or —
#   ./scripts/setup-server.sh

DEPLOY_PATH="${DEPLOY_PATH:-/opt/resonance}"
REPO="mark-219/resonance"
RUNNER_VERSION="2.322.0"

echo "╔══════════════════════════════════════╗"
echo "║     Resonance — Server Setup         ║"
echo "╚══════════════════════════════════════╝"
echo ""

# ─── 1. Clone repo ───────────────────────────────────────────────────

if [ -d "$DEPLOY_PATH/.git" ]; then
  echo "[1/4] Repo already cloned at $DEPLOY_PATH"
else
  echo "[1/4] Cloning repository..."
  sudo mkdir -p "$DEPLOY_PATH"
  sudo chown "$USER:$USER" "$DEPLOY_PATH"
  git clone "https://github.com/${REPO}.git" "$DEPLOY_PATH"
fi

cd "$DEPLOY_PATH"

# ─── 2. Generate .env ────────────────────────────────────────────────

if [ -f .env ]; then
  echo "[2/4] .env already exists — skipping"
else
  echo "[2/4] Generating production .env..."
  DB_PASSWORD=$(openssl rand -hex 24)
  SESSION_SECRET=$(openssl rand -hex 32)

  cat > .env <<EOF
# ─── Generated by setup-server.sh ─────────────────
DB_PASSWORD=${DB_PASSWORD}
SESSION_SECRET=${SESSION_SECRET}

# ─── OIDC (edit these for Authentik) ──────────────
OIDC_ISSUER=
OIDC_CLIENT_ID=
OIDC_CLIENT_SECRET=
OIDC_REDIRECT_URI=http://$(hostname -I | awk '{print $1}'):3100/auth/callback

# ─── Paths ────────────────────────────────────────
LOCAL_AUTH_ENABLED=true
CORS_ORIGIN=http://$(hostname -I | awk '{print $1}'):3100
SSH_KEY_DIR=~/.ssh
MUSIC_PATH=/mnt/music
EOF

  chmod 600 .env
  echo "  .env created with random secrets (permissions: 600)"
fi

# ─── 3. Install GitHub Actions runner ─────────────────────────────────

RUNNER_DIR="${DEPLOY_PATH}/.runner"

if [ -f "${RUNNER_DIR}/.runner" ]; then
  echo "[3/4] Runner already configured — skipping"
else
  echo "[3/4] Installing GitHub Actions self-hosted runner..."
  echo ""
  echo "  You need a runner registration token from:"
  echo "  https://github.com/${REPO}/settings/actions/runners/new"
  echo ""
  read -rp "  Paste the registration token: " RUNNER_TOKEN

  mkdir -p "$RUNNER_DIR"
  cd "$RUNNER_DIR"

  # Download runner
  ARCH=$(uname -m)
  case "$ARCH" in
    x86_64) RUNNER_ARCH="x64" ;;
    aarch64|arm64) RUNNER_ARCH="arm64" ;;
    *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
  esac

  RUNNER_TAR="actions-runner-linux-${RUNNER_ARCH}-${RUNNER_VERSION}.tar.gz"
  if [ ! -f "$RUNNER_TAR" ]; then
    curl -sL "https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/${RUNNER_TAR}" -o "$RUNNER_TAR"
  fi
  tar xzf "$RUNNER_TAR"

  # Configure
  ./config.sh \
    --url "https://github.com/${REPO}" \
    --token "$RUNNER_TOKEN" \
    --name "apps-$(hostname)" \
    --labels "self-hosted,linux,resonance" \
    --work "$DEPLOY_PATH/_work" \
    --unattended

  # Install as systemd service
  sudo ./svc.sh install
  sudo ./svc.sh start
  echo "  Runner installed and running as a systemd service"

  cd "$DEPLOY_PATH"
fi

# ─── 4. Configure GitHub repository variables ────────────────────────

echo "[4/4] Setup complete!"
echo ""
echo "  Next steps:"
echo ""
echo "  1. Set the DEPLOY_PATH variable in your GitHub repo:"
echo "     gh variable set DEPLOY_PATH --body '${DEPLOY_PATH}'"
echo "     (Settings → Environments → production → Variables)"
echo ""
echo "  2. Edit .env to configure OIDC and music paths:"
echo "     nano ${DEPLOY_PATH}/.env"
echo ""
echo "  3. Push to main to trigger the first deploy, or run manually:"
echo "     cd ${DEPLOY_PATH}"
echo "     docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build"
echo ""
